#
#  This file is part of QAOS.
#
#  This file is licensed under the GNU Lesser General Public License version 3 (LGPLv3).
#
#  You should have received a copy of GNU Lesser General Public License
#  along with QAOS. If not, see <https://www.gnu.org/licenses/>.
#
#  Copyright (c) 2025 by Kadir Aydın.
#



include ../../Make.inc


Build: Basis \
	

	@cp -r ^Conf/*  $(Out)/Conf



Basis:
	@rm -rf $(Out)

	@mkdir -p $(Out)/Moq
	@mkdir -p $(Out)/Log
	@mkdir -p $(Out)/Conf




Clean:
	@rm -rf $(Out)

